config/routes.rb
Wihis::Application.routes.draw do
  devise_for :users
  root :to => 'points#index'
  resources :points

  post '/get_address' => "points#get_address"
  get '/tags_autocomplete' => "tags#autocomplete"

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :point_id, :text, :user_id
  serialize :text
  belongs_to :user
  belongs_to :point

  def self.leave(user_id, point_id, data)
    self.create(:user_id => user_id,
                :point_id => point_id,
                :text => data)
  end
end

app/models/point.rb
class Point < ActiveRecord::Base

  has_and_belongs_to_many :tags
  has_many :activities

  #=================== Gmaps4Rails===================================
  acts_as_gmappable :process_geocoding => true, :validation => false
  before_create :address_presence
  #==================================================================

  #=================== Geocoder =====================================
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode
  #==================================================================

  attr_accessible :address, :gmaps, :description, :latitude, :longitude, :no_geocode, :tags
  attr_accessor :no_geocode


  def gmaps4rails_address
    address
  end

  #def gmaps4rails_infowindow
  #  "<h4>#{address}</h4>"
  #end

  def self.prepare_parameters(data)

    n_tags = []
    ex_tags = []
    tags = []
    out_tags =[]
    description = data[:description]

    unless data[:'tag-n'].blank?
      new_tags = data[:"tag-n"]
      new_tags.each do |tag|
        n_tags << Tag.new(:name => tag)
      end
      tags += new_tags
    end

    unless data[:tag].blank?
      exist_tag_ids = data[:tag].keys
      exist_tag_names = data[:tag].values
      ex_tags = Tag.where('id in (?)', exist_tag_ids)
      tags += exist_tag_names
    end

    data[:no_geocode] = true
    data[:tags] = n_tags + ex_tags
    data.delete(:tag)
    data.delete(:'tag-n')
    data.delete(:description)

    #return {:point => self.new(data), :tags => "<div class='tag-cnt'>" + tags.map{|a| "<div class='tag-item'>#{a}</div>"}.join() + "</div> #{description}"}
    return {:point => self.new(data), :tags => {:tags => tags, :desc => description}}

    #todo
    #  need to refactor
    #  need some tests

  end

  private

  def address_presence
    Point.acts_as_gmappable :process_geocoding => !self.address.blank? && !self.no_geocode, :validation => false
    return true
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :points
  attr_accessible :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :address, :first_name, :last_name, :username

  has_many :activities
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  def index
    @point = Point.new
    @json = build_map(Point.all)
  end

  def get_address
    @address = Geocoder.search(params[:"latLng"])[0].data["formatted_address"]
    render :text => @address
  end

  def create
    data = Point.prepare_parameters(params[:point])
    puts params[:point]
    @point = data[:point]

    if @point.save
      Activity.leave(current_user.id, @point.id, data[:tags])
      @json = build_map(@point)
      @center = {:longitude => params[:point]["longitude"], :latitude => params[:point]["latitude"] }

      respond_to do |format|
        format.html{redirect_to :action => :index}
        format.js
      end

      return
    else
      redirect_to :action => :index
      return
    end

    #  =======================================
    #
    #  Tag.find(:all, :conditions => ['tags.id not in (?)',Point.first.tags.find(:all, :select => 'tags.id').uniq.map {|x| x.id}] )
  end


  private

  def build_map(collection, options = {})
    collection.to_gmaps4rails do |point, marker|
      marker.infowindow render_to_string(:partial => "points/infowindow", :locals => {:point => point})
      #marker.title "#{city.name}"
      #marker.json({ :population => city.population})
      #options[:status] = point.status.blank? ? options[:status] : nil
      #status_dir = options[:status].blank? ? point.status : (point.status.blank? ? options[:status] : point.status)
      #width = options[:width].blank? ? 32 : options[:width]
      #height = options[:height].blank? ? 37 : options[:height]
      #marker.picture({:picture => "/assets/markers/#{status_dir}/pin-export.png",
      #                :width => width,
      #                :height => height})
    end
  end


end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def autocomplete
    result = Tag.where("name like ?", '%'+params[:term]+'%')
    text = []
    result.each do |el|
      text << {:id => "#{el.id}",
               :label => el.name,
               :value => el.name
      }
    end
    render :text => text.to_json
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/points_helper.rb
module PointsHelper
  def build_activity(text)
    html = "<div class='tag-cnt'>"
    text[:tags].each do |tag|
      html << "<div class='tag-item'>#{sanitize(tag)}</div>"
    end
    html << "</div>"
    html << sanitize(text[:desc])
    return raw html
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
  %span.icon-bar
  %span.icon-bar
%a.brand{:href => root_path} WIHIS
.container.nav-collapse
  %ul.nav
    %li

  %ul.nav.pull-right
    - if user_signed_in?
      %li.dropdown
        %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
          %i.icon-user.icon-white
          = current_user.email
          %b.caret
        %ul.dropdown-menu
          %li
            = link_to "Profile", edit_user_registration_path
          %li.divider
            %li
              = link_to "Sign out", destroy_user_session_path, :method => :delete

    - else
      %li
        %a{:href => new_user_session_path}
          Sign in

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Myapp"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag "application", :media => "all"
    = stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/cupertino/jquery-ui.css"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer
            = yield :scripts

app/views/points/_form.html.haml
= simple_form_for @point, :html => { :class => 'form-horizontal' } do |f|
  = f.input :latitude
  = f.input :longitude
  = f.input :description
  = f.input :address
  = f.input :gmaps
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), points_path, :class => 'btn'

app/views/points/_infowindow.html.haml
#infowindow
  %header
    .coordinates
      .latitude
        = point.latitude
      .longitude
        = point.longitude
    .address
      %h5.address
        = point.address
  -#%h5
    Description:
    = point.description

  .control-group
    .controls
      - point.tags.each do |tag|
        %input{:type => "text", :name => "point[tag][#{tag.id}]", :value => "#{tag.name}", :class => "tag"}

  #activities
    - point.activities.each do |activity|
      %table
        %tr.activity
          %td{:width => 130, :class => "log"}
            .login
              = activity.user.email
              .date
                = activity.created_at.strftime("%Y-%m-%d %H:%M")
          %td{:class => "cnt"}
            .cont
              = build_activity activity.text

app/views/points/create.js.erb
clearOverlays();
Gmaps.map.addMarkers(<%= raw @json %>);
Gmaps.map.callback();
Gmaps.map.map.setCenter(new google.maps.LatLng(<%= @center[:latitude]%>, <%=@center[:longitude]%>));
Gmaps.map.map.setZoom(15);

var last_marker = Gmaps.map.markers[Gmaps.map.markers.length - 1];
last_marker.infowindow.open(Gmaps.map.map, last_marker.serviceObject);

apply_tagging();

app/views/points/edit.html.haml
- model_class = Point
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/points/index.html.haml
= gmaps4rails(@json)

#popup-form{:style => "display:none"}
  %div{:class => "popup ui-widget"}
    = form_for @point, :remote => true do |f|
      %header
        .coordinates  
          %div.latitude
          %div.longitude
        .address
          %h5.address
      %section
        = f.hidden_field :latitude
        = f.hidden_field :longitude
        = f.hidden_field :address
         
        .control-group
          .controls
            .pholder
              #def_text
                Add tags  
            %input{:type => "text", :name => 'point[tag][]', :value => "", :class => "tag"}
        .control-group
          = f.label :comments
          .controls
            = f.text_area :description ,:rows => 4, :cols => 50, :style => "width: 482px; height: 95px;resize: none;"
      .pos      
        %button{:class => 'btn btn-primary', :onclick => 'validate_form()', :disabled => "disabled" }
          Create Point

app/views/points/new.html.haml
- model_class = Point
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/points/show.html.haml
- model_class = Point
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:latitude) + ':'
  %br
  = @point.latitude
%p
  %strong= model_class.human_attribute_name(:longitude) + ':'
  %br
  = @point.longitude
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @point.description
%p
  %strong= model_class.human_attribute_name(:address) + ':'
  %br
  = @point.address
%p
  %strong= model_class.human_attribute_name(:gmaps) + ':'
  %br
  = @point.gmaps

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), points_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_point_path(@point), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), point_path(@point), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'